shreck_quotes = [
    "Ogres are like onions. We have layers! 🧅✨",
    "Believe in the beauty within. 🌟💚",
    "Even an ogre can find love. 💖🌻",
    "Keep on dreaming, Donkey! 🐴🌈",
    "Every swamp has its beauty. 🌿💧",
    "You don’t have to be a prince to be charming. 🏰💫",
    "True love’s kiss can break any spell. 💋🔮",
    "You’re unique, just like me! 👑🐉",
    "Home is where your swamp is. 🏡🛶",
    "Dream big, even if you’re an ogre! 💤💚",
    "You can change your story. 📖🔄",
    "Friendship knows no bounds. 🤝✨",
    "Beauty is in the eye of the ogre. 👀💚",
    "Find the fairy tale in your life. 📜🌟",
    "Stand tall, even in the mud. 🦶🌧",
    "Believe in yourself, even when others don’t. 🌟🧅",
    "Never judge an ogre by its layers. 🧅👀",
    "Embrace your inner ogre. 💪💚",
    "Make your own happily ever after. 🏰💖",
    "Be proud of who you are, ogre or not! 🌟💚",
    "Find the magic in everyday life. 🪄✨",
    "True friends stick together through thick and thin. 👫💫",
    "Live life one swamp at a time. 🌿💚",
    "Adventure awaits beyond the swamp. 🌍✨",
    "Turn your dreams into fairy tales. 🏰🌟",
    "You are stronger than any dragon. 🐉💪",
    "Your heart is your greatest treasure. 💖🏴‍☠️",
    "Be yourself, everyone else is taken. 🌟💚",
    "It’s okay to be different. 🧅🌈",
    "Every day is a new adventure. 🚀🌟",
    "The journey is just as important as the destination. 🛣✨",
    "Embrace the unexpected. 🌟💚",
    "You can conquer any challenge. 🐉💪",
    "True beauty comes from within. 💖💫",
    "Find joy in the simple things. 🌼🌟",
    "Be brave, even in the face of dragons. 🐉💪",
    "Don’t be afraid to take the leap. 🌟✨",
    "You are your own fairy tale. 📖🌟",
    "Keep moving forward, no matter what. 🚶‍♂️✨",
    "Believe in your own happily ever after. 🏰💖",
    "Find your strength in the swamp. 🌿💪",
    "You are more than you think you are. 🌟💚",
    "Love yourself, layers and all. 💖🧅",
    "Every day is a new chapter in your fairy tale. 📖🌟",
    "Stand up for what you believe in. 🌟💚",
    "Let your heart guide your way. 💖🧭",
    "Embrace the journey, not just the destination. 🛤✨",
    "You have the power to change your story. 🏰📖",
    "Find magic in the mundane. 🪄💫",
    "Follow your heart, no matter where it leads. 💖✨",
    "You are the hero of your own story. 🦸‍♂️🌟",
    "True friends make the journey worthwhile. 🤝💫",
    "Discover the beauty in the unexpected. 🌟💚",
    "Never stop believing in fairy tales. 🏰🌟",
    "Find strength in your inner ogre. 💪💚",
    "Make each day a new adventure. 🚀✨",
    "The greatest treasure lies within. 💖🏴‍☠️",
    "You are unique, embrace it! 🌟💚",
    "Every swamp has its own beauty. 🌿💫",
    "Find the fairy tale in your everyday life. 📖🌟",
    "Embrace your inner dragon slayer. 🐉💪",
    "Believe in your own magic. 🪄✨",
    "True love is worth the journey. 💖🏰",
    "Stand tall, even in the mud. 🌧💪",
    "You are more than your layers. 🧅💚",
    "Find joy in your own story. 📖🌟",
    "You can conquer any obstacle. 🐉💪",
    "Every day is a chance to start anew. 🕛✨",
    "Believe in the magic within you. 🪄💫",
    "True beauty comes from the heart. 💖🌟",
    "Make your own happily ever after. 🏰💖",
    "Find strength in your own story. 📖💪",
    "You are your own fairy tale hero. 🦸‍♀️🌟",
    "Embrace the adventure of life. 🚀✨",
    "You are capable of great things. 🌟💚",
    "Every moment is a new beginning. 🕛✨",
    "Believe in the power of love. 💖🌟",
    "True friends are the best treasure. 🤝💫",
    "Find the magic in your own story. 📖✨",
    "Stand up for what matters to you. 💪🌟",
    "You are stronger than you think. 🌟💚",
    "Embrace the journey, not just the goal. 🚶‍♀️✨",
    "You have the power to change your life. 🏰📖",
    "Find joy in the simple moments. 🌼✨",
    "Every day is a new chapter. 📖✨",
    "You are the hero of your fairy tale. 🦸‍♂️🌟",
    "Believe in the beauty of your dreams. 🌟💚",
    "True love can conquer anything. 💖🏰",
    "Make your own magic every day. 🪄✨",
    "Find the beauty in the ordinary. 🌼🌟",
    "You are capable of amazing things. 🌟💚",
    "Every journey begins with a single step. 🛤✨",
    "Believe in your own power. 💪🌟",
    "True friends are a treasure. 🤝💫",
    "Find the magic in the everyday. 🪄🌟",
    "Stand up for your dreams. 🦸‍♀️💪",
    "You are more than your layers. 🧅💚",
    "Embrace your own story. 📖✨",
    "You are the author of your fairy tale. ✍️🌟"
]